#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

until cd /app
do
    echo "Waiting for server volume..."
done

#until ./manage.py migrate
#do
#    echo "Waiting for db to be ready..."
#    sleep 2
#done

python manage.py collectstatic --noinput
python manage.py migrate
python manage.py compilemessages

#gunicorn config.wsgi --bind 0.0.0.0:8000 --workers 1
echo "Starting daphne!"
daphne config.asgi:application -b 0.0.0.0 -p 8000
