# Generated by Django 3.2 on 2022-09-20 14:20

import api.users.auth.external_token.token
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_provider',
            field=models.CharField(blank=True, choices=[('WH', 'WhatsApp'), ('SMS', 'SMS')], default='SMS', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.CreateModel(
            name='ExternalAuthenticationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified.', verbose_name='modified at')),
                ('deleted', models.BooleanField(default=False, help_text='Set to False when an element is deleted')),
                ('provider', models.CharField(blank=True, choices=[('WH', 'WhatsApp'), ('SMS', 'SMS')], max_length=5, null=True)),
                ('token', models.CharField(default=api.users.auth.external_token.token.random_token, max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_authentication_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
