# Generated by Django 3.2 on 2022-09-27 11:14

import api.users.auth.external_token.token
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalauthenticationtoken',
            name='provider',
            field=models.CharField(choices=[('WH', 'WhatsApp'), ('SMS', 'SMS')], default='SMS', max_length=5),
        ),
        migrations.AlterField(
            model_name='externalauthenticationtoken',
            name='token',
            field=models.CharField(blank=True, default=api.users.auth.external_token.token.random_token, max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_provider',
            field=models.CharField(blank=True, choices=[('WH', 'WhatsApp'), ('SMS', 'SMS')], default='SMS', max_length=10),
        ),
    ]
