# Generated by Django 3.2 on 2022-09-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220927_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalauthenticationtoken',
            name='provider',
            field=models.CharField(choices=[('WH', 'WhatsApp'), ('SMS', 'SMS'), ('D', 'CONSOLE')], default='SMS', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_provider',
            field=models.CharField(choices=[('WH', 'WhatsApp'), ('SMS', 'SMS'), ('D', 'CONSOLE')], default='SMS', max_length=10),
        ),
    ]
