# Generated by Django 3.2 on 2022-09-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220927_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalauthenticationtoken',
            name='type',
            field=models.CharField(choices=[('VA', 'VA'), ('SI', 'Sign in')], default='SI', max_length=5),
        ),
        migrations.AlterField(
            model_name='externalauthenticationtoken',
            name='provider',
            field=models.CharField(choices=[('WH', 'WhatsApp'), ('SMS', 'SMS'), ('D', 'Console')], default='SMS', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_provider',
            field=models.CharField(choices=[('WH', 'WhatsApp'), ('SMS', 'SMS'), ('D', 'Console')], default='SMS', max_length=10),
        ),
    ]
