# Generated by Django 3.2 on 2022-09-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220927_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalauthenticationtoken',
            name='type',
            field=models.CharField(choices=[('VA', 'Validate account'), ('SI', 'Sign in')], default='SI', max_length=5),
        ),
    ]
