# Generated by Django 3.2 on 2022-09-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_externalauthenticationtoken_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language_code',
            field=models.CharField(default='es', max_length=5),
        ),
    ]
