# Generated by Django 3.2 on 2023-01-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_identityfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityfiles',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
