# Generated by Django 3.2 on 2023-01-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20230118_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
