# Generated by Django 3.2 on 2023-01-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_identity_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
