# Generated by Django 3.2 on 2023-01-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_identity_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('A', 'Admin'), ('SP', 'Support'), ('ST', 'Standard'), ('SU', 'Superuser')], max_length=5, null=True),
        ),
    ]
