# Generated by Django 3.2 on 2023-01-25 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.documenttype'),
        ),
    ]
