# Generated by Django 3.2 on 2023-02-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20230208_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
