# Generated by Django 3.2 on 2023-02-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance_currency',
        ),
    ]
