# Generated by Django 3.2 on 2023-03-03 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20230220_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner_referred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_user', to=settings.AUTH_USER_MODEL),
        ),
        # migrations.AddField(
        #     model_name='user',
        #     name='referred_link',
        #     field=models.CharField(blank=True, max_length=200, null=True),
        # ),
    ]
