# Generated by Django 3.2 on 2023-03-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_user_owner_referred'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_investment',
            field=models.BooleanField(default=True),
        ),
    ]
