# Generated by Django 3.2 on 2023-03-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_user_is_first_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_refer',
            field=models.BooleanField(default=False),
        ),
    ]
