# Generated by Django 3.2 on 2025-10-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_user_can_refer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['phone_number']},
        ),
        migrations.AddField(
            model_name='user',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
