# Generated by Django 3.2 on 2025-10-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20251006_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_refer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='owner_referred',
        ),
    ]
