# Generated by Django 6.0.4 on 2026-05-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_externalauthenticationtoken_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalAuthenticationToken',
        ),
    ]
